messaging:
  kafka:
    bootstrap-servers:localhost:9092
    schema-registry-url:http://localhost:8081  
  topics:
    registration-requested: registration-requested
    registration-submitted: registration-submitted
    registration-administered: registration-administered




